from setuptools import setup, find_packages

setup(
    name="aclimate_v3_historical_spatial_etl",
    version='v3.0.0',
    author="santiago123x",
    author_email="s.calderon@cgiar.com",
    description="ETL pipeline designed to download, extract, and prepare historical spatial data for integration into GeoServer.",
    url="https://github.com/CIAT-DAPA/aclimate_v3_historical_spatial_etl",
    download_url="https://github.com/CIAT-DAPA/aclimate_v3_historical_spatial_etl",
    packages=find_packages('src'),
    package_dir={'': 'src'},
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.10",
    entry_points={
        'console_scripts': [
            'aclimate_v3_historical_spatial_etl=aclimate_v3_historical_spatial_etl.aclimate_run_etl:main',
        ],
    },
    install_requires=[
        "affine==2.4.0",
        "attrs==25.3.0",
        "cdsapi==0.7.6",
        "certifi==2025.4.26",
        "cftime==1.6.4.post1",
        "charset-normalizer==3.4.2",
        "click==8.2.0",
        "click-plugins==1.1.1",
        "cligj==0.7.2",
        "colorama==0.4.6",
        "dotenv==0.9.9",
        "ecmwf-datastores-client==0.1.0",
        "exceptiongroup==1.3.0",
        "geopandas==1.0.1",
        "greenlet==3.2.2",
        "gsconfig-py3==1.0.7",
        "h5netcdf==1.6.1",
        "h5py==3.13.0",
        "idna==3.10",
        "iniconfig==2.1.0",
        "multiurl==0.3.5",
        "netCDF4==1.7.2",
        "numpy==2.2.6",
        "packaging==25.0",
        "pandas==2.2.3",
        "pluggy==1.6.0",
        "psycopg2==2.9.10",
        "pyogrio==0.11.0",
        "pyparsing==3.2.3",
        "pyproj==3.7.1",
        "pytest==8.3.5",
        "python-dateutil==2.9.0.post0",
        "python-dotenv==1.1.0",
        "pytz==2025.2",
        "rasterio==1.4.3",
        "requests==2.32.3",
        "rioxarray==0.19.0",
        "shapely==2.1.1",
        "six==1.17.0",
        "SQLAlchemy==2.0.41",
        "tomli==2.2.1",
        "tqdm==4.67.1",
        "typing_extensions==4.13.2",
        "tzdata==2025.2",
        "urllib3==2.4.0",
        "xarray==2025.4.0",
    ]
)